# Generated by Django 4.0.4 on 2024-05-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.ImageField(null=True, upload_to='profile_picture'),
        ),
    ]
