# Generated by Django 4.0.4 on 2024-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.ImageField(default='profile_picture/download_EPBN0x6.jpg', upload_to='profile_picture'),
        ),
    ]
