# Generated by Django 4.0.4 on 2024-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Funds Added'), (2, 'Funds Subtracted'), (3, 'Driver Account')]),
        ),
    ]
