# Generated by Django 4.0.4 on 2024-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
