# Generated by Django 4.0.4 on 2024-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_picture',
            field=models.ImageField(default='profile_picture/edit.png', upload_to='profile_picture'),
        ),
    ]
