# Generated by Django 4.0.4 on 2024-05-25 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_ride_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
