# Generated by Django 4.0.4 on 2024-06-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_alter_ride_options_alter_ride_distance_covered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
